# Package definition for lazygit

package_name: lazygit
github_repo: jesseduffield/lazygit
license: MIT
artifact_format: tar.gz
description: "simple terminal UI for git commands"
license: MIT

# Build for all Debian suites and all supported architectures.
